userNumber= 50;
var userGuess;
crystals= 12;

var correctGuess = false;

//game counters
var winCount= 0;
var lossCount = 0;
var totalScore;

//A win is recorded when players choose from the 4 crystals, which spit out a random number between 1 and 10 and the numbers will need to add up to the random number generated by the master number which is to be between 11 and 60. If they go over, they get a loss. 

$(document).ready(function(){

   $(function() {
        $(".randomNumber").html(Math.floor(Math.random() * 60) + 1);
   



	

	$(".diamond").click(function() {
		$(".score").html(Math.ceil(Math.random() * 12))+1;
		
		

	});

 });


});



